variables:
  azureSubscription: 'AZR-RWD-PRD1'
  docker.imageName: 'eprcalculatorfrontend'
  acr.azureContainerRegistryName: 'prdrwdinfac1401'
  acr.repositoryName: 'eprcalculatorfrontendrepository'
  serviceName: 'PRDRWDWEBWA1421'
